# Generated by Django 4.2.1 on 2026-01-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_category_alter_product_options_product_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=125),
        ),
    ]
